# Site settings
title: Granite.code
baseurl: "/granite.code" # the subpath of your site, e.g. /blog/
url: "https://jimmac.github.io" # the base hostname & protocol for your site
sourceurl: "https://github.com/Granite-Code/granitecode.github.io"
description: "AI code assistant"

permalink: /:title/

# Build settings
markdown: kramdown
